version: '3.9'
networks:
  api_network_private:
    driver: bridge
  api_network_public:
    driver: bridge
services:
  api_csharp:
    build:
      context: .
      dockerfile: Dockerfile
    image: api_csharp
    container_name: api_csharp
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_USERNAME=$DATABASE_USERNAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
    ports:
      - "80:80"
    networks:
      - api_network_private
      - api_network_public
    command: ./wait-for-it.sh $DATABASE_HOST:$DATABASE_PORT -- /app 
