version: '3.9'
networks:
  api_network_private:
    driver: bridge
  api_network_public:
    driver: bridge
services:
  api_csharp:
    build:
      context: .docker/
      dockerfile: Dockerfile
    container_name: api_csharp_container
    image: api_csharp
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_USERNAME=$DATABASE_USERNAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
    ports:
      - "44326:44326"
    networks:
      - api_network_private
      - api_network_public
    command: ./wait-for-it.sh $DATABASE_HOST:$DATABASE_PORT -- /app 
  api_proxy:
    build: ./nginx
    container_name: api_csharp_proxy_container
    image: api_proxy
    ports:
      - "80:80"
    networks:
      - api_network_public
    links:
      - api_csharp
