version: '3'
services:
  api_csharp:
    build:
      context: .
      dockerfile: Dockerfile
    image: api_csharp
    container_name: api_csharp
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_USERNAME=$DATABASE_USERNAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
    ports:
      - "8080:80"
    networks:
      - api-network
    command: ./wait-for-it.sh $DATABASE_HOST:$DATABASE_PORT -- /app 
networks:
  api-network:
    driver: bridge
volumes:
  node_modules:        